name: CI

on: [push, pull_request]

jobs:
  ci:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.3', '7.4', '8.0']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set git config
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
        if: runner.os == 'Windows'

      - uses: actions/checkout@v2

      - name: Setup PHP${{ matrix.php-version }}@${{ matrix.os }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          extensions: json, curl, libxml, simplexml, openssl

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-version

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies on PHP(=7.2)@${{ matrix.os }}
        if: matrix.php-version == '7.2'
        id: dependencies-cache-72
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-php${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-

      - name: Cache dependencies on PHP(>7.2)@${{ matrix.os }}
        if: matrix.php-version != '7.2'
        id: dependencies-cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - run: vendor/bin/phpstan analyse --no-progress

      - run: make keygen

      - run: vendor/bin/phpunit

      - run: make clean
